### ISSUE TITLE
Promisify

### ISSUE THREAD

**Issue by ghost** [iamstarkov/get-tweets#13]
May be rewrite module with promises? This will allow to use promise chains and async/await

``` js
getTweets(tokens, 'largescalejs_ru', '424119506508980224').then(tweets => {
  console.log(tweets);
});
```

``` js
async function getTweets() {
  const tweets = await getTweets(tokens, 'largescalejs_ru', '424119506508980224');
  console.log(tweets);
}
```

**Comment by iamstarkov** [comment]
do you know how to handle errors with awaits?

**Comment by andrepolischuk** [comment]
Tr

**Comment by ghost** [comment]
try ... catch

Like the third example http://tc39.github.io/ecmascript-asyncawait/#examples

**Comment by iamstarkov** [comment]
oh, its pretty ugly and wont be v8-optimised

**Comment by ghost** [comment]
So, may I rewrite or no?

**Comment by iamstarkov** [comment]
sure, i wanted to search for another promise issue you created, but failed. feel free to rewrite above promises
